/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorsIndexRouteImport } from './routes/mentors.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as MentorsMentorIdRouteImport } from './routes/mentors.$mentorId'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard/schedule'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard/courses.index'
import { Route as DashboardCoursesCreateRouteImport } from './routes/dashboard/courses.create'
import { Route as DashboardCoursesCourseIdManageRouteImport } from './routes/dashboard/courses.$courseId.manage'
import { Route as DashboardCoursesCourseIdLearnRouteImport } from './routes/dashboard/courses.$courseId.learn'
import { Route as DashboardCoursesCourseIdEditRouteImport } from './routes/dashboard/courses.$courseId.edit'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const MentorsMentorIdRoute = MentorsMentorIdRouteImport.update({
  id: '/$mentorId',
  path: '/$mentorId',
  getParentRoute: () => MentorsRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardCoursesCreateRoute = DashboardCoursesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardCoursesCourseIdManageRoute =
  DashboardCoursesCourseIdManageRouteImport.update({
    id: '/$courseId/manage',
    path: '/$courseId/manage',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdLearnRoute =
  DashboardCoursesCourseIdLearnRouteImport.update({
    id: '/$courseId/learn',
    path: '/$courseId/learn',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdEditRoute =
  DashboardCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/dashboard/courses/create': typeof DashboardCoursesCreateRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
  '/dashboard/courses/$courseId/learn': typeof DashboardCoursesCourseIdLearnRoute
  '/dashboard/courses/$courseId/manage': typeof DashboardCoursesCourseIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/dashboard/courses/create': typeof DashboardCoursesCreateRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
  '/dashboard/courses/$courseId/learn': typeof DashboardCoursesCourseIdLearnRoute
  '/dashboard/courses/$courseId/manage': typeof DashboardCoursesCourseIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/dashboard/courses/create': typeof DashboardCoursesCreateRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditRoute
  '/dashboard/courses/$courseId/learn': typeof DashboardCoursesCourseIdLearnRoute
  '/dashboard/courses/$courseId/manage': typeof DashboardCoursesCourseIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certification'
    | '/courses'
    | '/dashboard'
    | '/enterprise'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/dashboard/courses'
    | '/dashboard/messages'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/mentors/$mentorId'
    | '/courses/'
    | '/dashboard/'
    | '/mentors/'
    | '/dashboard/courses/create'
    | '/dashboard/courses/'
    | '/dashboard/courses/$courseId/edit'
    | '/dashboard/courses/$courseId/learn'
    | '/dashboard/courses/$courseId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certification'
    | '/enterprise'
    | '/login'
    | '/pricing'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/dashboard/messages'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/mentors/$mentorId'
    | '/courses'
    | '/dashboard'
    | '/mentors'
    | '/dashboard/courses/create'
    | '/dashboard/courses'
    | '/dashboard/courses/$courseId/edit'
    | '/dashboard/courses/$courseId/learn'
    | '/dashboard/courses/$courseId/manage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certification'
    | '/courses'
    | '/dashboard'
    | '/enterprise'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/dashboard/courses'
    | '/dashboard/messages'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/mentors/$mentorId'
    | '/courses/'
    | '/dashboard/'
    | '/mentors/'
    | '/dashboard/courses/create'
    | '/dashboard/courses/'
    | '/dashboard/courses/$courseId/edit'
    | '/dashboard/courses/$courseId/learn'
    | '/dashboard/courses/$courseId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificationRoute: typeof CertificationRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRouteWithChildren
  PricingRoute: typeof PricingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/mentors/$mentorId': {
      id: '/mentors/$mentorId'
      path: '/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof MentorsMentorIdRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/create': {
      id: '/dashboard/courses/create'
      path: '/create'
      fullPath: '/dashboard/courses/create'
      preLoaderRoute: typeof DashboardCoursesCreateRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/manage': {
      id: '/dashboard/courses/$courseId/manage'
      path: '/$courseId/manage'
      fullPath: '/dashboard/courses/$courseId/manage'
      preLoaderRoute: typeof DashboardCoursesCourseIdManageRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/learn': {
      id: '/dashboard/courses/$courseId/learn'
      path: '/$courseId/learn'
      fullPath: '/dashboard/courses/$courseId/learn'
      preLoaderRoute: typeof DashboardCoursesCourseIdLearnRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/edit': {
      id: '/dashboard/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/dashboard/courses/$courseId/edit'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DashboardCoursesRouteChildren {
  DashboardCoursesCreateRoute: typeof DashboardCoursesCreateRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardCoursesCourseIdEditRoute: typeof DashboardCoursesCourseIdEditRoute
  DashboardCoursesCourseIdLearnRoute: typeof DashboardCoursesCourseIdLearnRoute
  DashboardCoursesCourseIdManageRoute: typeof DashboardCoursesCourseIdManageRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesCreateRoute: DashboardCoursesCreateRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardCoursesCourseIdEditRoute: DashboardCoursesCourseIdEditRoute,
  DashboardCoursesCourseIdLearnRoute: DashboardCoursesCourseIdLearnRoute,
  DashboardCoursesCourseIdManageRoute: DashboardCoursesCourseIdManageRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MentorsRouteChildren {
  MentorsMentorIdRoute: typeof MentorsMentorIdRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
}

const MentorsRouteChildren: MentorsRouteChildren = {
  MentorsMentorIdRoute: MentorsMentorIdRoute,
  MentorsIndexRoute: MentorsIndexRoute,
}

const MentorsRouteWithChildren =
  MentorsRoute._addFileChildren(MentorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificationRoute: CertificationRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRouteWithChildren,
  PricingRoute: PricingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
